### ISSUE TITLE
RuntimeException ClassNotFoundException ModifierHighlighterAnnotator

### ISSUE THREAD

**Issue by Mikulas** [nextras/orm-intellij#1]
Errors thrown when loaded a78ddcf6e814b529d1ae28a0566103be76ebc9f4 to PhpStorm 10.0.3 143.1480 as zip

```
10:14:24 RuntimeException: java.lang.ClassNotFoundException: org.nextras.orm.intellij.annotator.ModifierHighlighterAnnotator PluginClassLoader[org.nextras.orm.intellij, 0.2]
10:14:29 PluginException: class with name "org.nextras.orm.intellij.actions.generation.GenerateGettersAction" not found [Plugin: org.nextras.orm.intellij]
10:14:49 Throwable: Null child action in group Generate () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=ormGenerateGettersAction
```

**Comment by hrach** [comment]
Dost divne :| https://github.com/nextras/orm-intellij/blob/master/src/org/nextras/orm/intellij/actions/generation/GenerateGettersAction.java Mam stable 10.0.2 a je to ok. Vcera jsem si to aktualizoval pres plugins.jetbrains.com.

**Comment by hrach** [comment]
Nechces si to zkusit zkompilovat sam? :)

**Comment by Mikulas** [comment]
Ok omlouvam se, když stáhnu jar z http://plugins.jetbrains.com/plugin/7912?utm_source=twitterfeed&utm_medium=twitter tak to jde… :)

**Comment by hrach** [comment]
:+1:
