### ISSUE TITLE
Fix support for PhpStorm 2019.2

### ISSUE THREAD

**Issue by majun** [nextras/orm-intellij#11]
Hi, I try to upgrade PhpStorm 2019.1.3 to version 2019.2. But there is problem with plugin compatibility, see screenshot.
![IDE and Plugin Updates 2019-08-14 13-28-50](https://user-images.githubusercontent.com/952656/63018326-d76c0d80-be98-11e9-9877-032d5098a923.png)
Could you try to fix it? Thanks!

**Comment by hrach** [comment]
Thanks for the report, looking into this.

**Comment by hrach** [comment]
Fixed https://github.com/nextras/orm-intellij/commit/8b89423627e3601ebb49b65dd353963e434b96f8. Plugin should be available in plugins repository within hours-max 2 days.

**Comment by hrach** [comment]
eventually you may download it here: https://github.com/nextras/orm-intellij/releases/tag/v0.5.1
