### ISSUE TITLE
No autocompletion when not using this->

### ISSUE THREAD

**Issue by hrach** [nextras/orm-intellij#16]
Hi :wave:,
this question/issue mainly affects phpstorm plugin. Not the library itself.

:warning: **Problem**
I'm having trouble with `Cmd + Click` or suggestions in `findBy` and similar methods.

:eyes: **Observations**
Suggestions are working with `this->` prefix which is now deprecated.
They do not work without `this->` prefix.

With `this->`
![image](https://user-images.githubusercontent.com/22822651/101546567-44b68280-39a9-11eb-9a6c-dd61af01dd44.png)

Without `this->`
![image](https://user-images.githubusercontent.com/22822651/101546627-5dbf3380-39a9-11eb-9167-fdde68a05d99.png)

:computer: **Env**
Plugin version 0.7.1, phpstorm 2020.3RC, Linux

:question: **Question**
How do I fix this? Is this a known bug?

_Originally posted by @mrceperka in https://github.com/nextras/orm/discussions/474_

**Comment by mrceperka** [comment]
Fixed by `Invalidate Caches`

**Comment by hrach** [comment]
Well, plugin installation forces new reindes, however when you update Orm only, it won't happen. We should change the code to handle both Orm versions at one.

**Comment by hrach** [comment]
Closing as there is a solution.
