### ISSUE TITLE
Result of IModel->getRepository() has to be stored in variable to work properly

### ISSUE THREAD

**Issue by mabar** [nextras/orm-intellij#20]
It's required to store `getRepository()` result in variable or otherwise plugin does not provide informations related to given repository entities (e.g. UserRepository + User entity)

With variable assignment, `$user` is `User`
```php
$userRepository = $this->model->getRepository(UserRepository::class);
$user = $userRepository->getByIdChecked(1);
assert($user instanceof User);
```

Without variable assignment, `$user` is `IEntity`
```php
$user = $this->model->getRepository(UserRepository::class)->getByIdChecked(1);
assert($user instanceof IEntity);
```

Related to #18

**Comment by hrach** [comment]
Released as 0.8.1: https://github.com/nextras/orm-intellij/releases/tag/v0.8.1
